### ISSUE TITLE
2018.01.第一周

### ISSUE THREAD

**Issue by ElevenEve** [ElevenEve/ISSUES#14]
- [x] BUG #39263::【0.7.2】【新增】【技能】增加一个新的被动技能效果，用于天书寻主奖励 必须完成
 - [x] BUG #39268::【优化】【红名】红名状态下死亡扣除的货币通过邮件通知玩家 必须完成
 - [x] BUG #37945::【0.7.2】【世界boss】剑冢相关 必须完成
 - [x] BUG #39318::【优化】【红名】增加一个配置指定场景内不走红名规则 必须完成
 - [x] BUG #39326::【优化】【世界boss】修改世界boss的怪物刷新公告规则 必须完成
 - [x] BUG #39347::【0.7.2】【bug】【日常】击杀魂殿boss会计算世界boss进度 必须完成
 - [x] BUG #39369::【0.7.2】【优化】【剑魂】增加一个仙火降临的购买奖励 必须完成

**Comment by ElevenEve** [comment]
- [x] BUG #39310::【0.7.2】【bug】【仙盟】副盟主无法踢人和修改自动批准操作 必须完成
  - [x] BUG #39231::【0.7.2】【bug】【后台】三域战场与九层妖塔参与时间不对 必须完成
  - [x] BUG #39211::【0.7.2】【优化】【战斗飘字】优化战斗飘字的表现 必须完成
  - [x] BUG #39411::【优化】【红名】红名在被杀死时发送一个系统公告 必须完成
  - [x] BUG #39395::【0.7.2】【优化】【仙盟】仙盟boss的消耗和召唤次数挂钩 必须完成
  - [x] BUG #39051::【0.7.2】【bug】【修仙论道】修仙论道选中玩家问题 必须完成
  - [x] BUG #39267::【0.7.2】【优化】【报表】新增仙盟篝火相关报表 必须完成
  - [x] BUG #39073::【0.7.2】【优化】【世界boss】世界boss记录增加一个地图的记录及掉落道具的链接 必须完成
